# Generated by Django 3.1.2 on 2020-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201008_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='post_pics'),
            preserve_default=False,
        ),
    ]
